#!/usr/bin/env expect

source common.tcl
set timeout -1

spawn pdp11

simh "set cpu 11/70"
simh "set cpu 1M"
simh "set cpu idle"
simh "attach tm0 pwb_sys.tap"
simh "set rp0 rp06"
simh "attach rp0 rp0"
simh "dep system sr 173030"
simh "boot rp0"

respond "#" "00"
respond "=" "unixhptm\r"

unix "cd /"
unix "mkfs /dev/rrp2 35000"
unix "labelit /dev/rrp2 sys p0003"
unix "mount /dev/rp2 /sys"
unix "cd /sys"
unix "cpio -idm </dev/rmt4"

unix "ed /etc/rc"
sendline "\$a"
sendline "mount /dev/rp1 /usr"
sendline "mount /dev/rp2 /sys"
sendline "."
sendline "w"
sendline "q"

unix "ed /etc/checklist"
sendline "\$a"
sendline "/dev/rrp1"
sendline "/dev/rrp2"
sendline "."
sendline "w"
sendline "q"

unix "ln /unixhptm /unix"
unix "echo /bin:/etc:/:/usr/bin > /.path"

unix "sync"
unix "sync"
unix "sync"

respond "# " $break
simh "quit"
expect eof
